Add doc how-to-use-bandchain-in-evm-contract.md
bandprotocol/bandchain-docs pull request #6
Opened 2023-06-01 06:29 UTC by colmazia

2023-06-01 06:55 UTC, babybunn commented
```
curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_IZhHdfXOBowf9qZryNxWdoWg8UfD/CCvZDwbKzW
```

2023-06-02 06:54 UTC, RogerKSI commented on docs/develop/02-developer-guides/how-to-use-bandchain-in-evm-contract.md
> +Let's look at the standard Oracle Script from band in our testnet [Band Protocol's Cryptocurrency Standard Dataset](https://laozi-testnet6.cosmoscan.io/oracle-script/401)
explain a bit on what's the purpose of this oracle script?

2023-06-02 06:55 UTC, RogerKSI commented on docs/develop/02-developer-guides/how-to-use-bandchain-in-evm-contract.md
> +Then heads to the bottom section and select Make New Request
Should we add some highlights on the button name? now, it's like a text.

```suggestion
Then heads to the bottom section and select "Make New Request"
```

2023-06-02 06:56 UTC, RogerKSI commented on docs/develop/02-developer-guides/how-to-use-bandchain-in-evm-contract.md
> +![](https://hackmd.io/_uploads/BJCsRqHLn.png)
all images are very big

2023-06-02 06:56 UTC, RogerKSI commented on docs/develop/02-developer-guides/how-to-use-bandchain-in-evm-contract.md
> +![](https://hackmd.io/_uploads/BJCsRqHLn.png)
it's a bit hard to read.

2023-06-02 06:58 UTC, RogerKSI commented on docs/develop/02-developer-guides/how-to-use-bandchain-in-evm-contract.md
> +If you are not sure what is the appropriate number, you can input 0.
I think we should give them a recommended number. maybe check with the service team

2023-06-02 07:00 UTC, RogerKSI commented on docs/develop/02-developer-guides/how-to-use-bandchain-in-evm-contract.md
> +In essence, a Bridge Contract is a smart contract facilitated by Band Protocol, designed to validate the authenticity of data received by your contract across various blockchains. A list of supported
Note: use new link once available.

2023-06-02 07:03 UTC, RogerKSI commented on docs/develop/02-developer-guides/how-to-use-bandchain-in-evm-contract.md
> +Band Protocol also provides additional libraries, such as Pyband and Bandchain.js, that aid in building data-relaying programs. You can explore more about these resources on their respective pages he
add link t

2023-06-02 07:09 UTC, colmazia commented on docs/develop/02-developer-guides/how-to-use-bandchain-in-evm-contract.md
> +Let's look at the standard Oracle Script from band in our testnet [Band Protocol's Cryptocurrency Standard Dataset](https://laozi-testnet6.cosmoscan.io/oracle-script/401)
ok

2023-06-02 07:10 UTC, colmazia commented on docs/develop/02-developer-guides/how-to-use-bandchain-in-evm-contract.md
> +Then heads to the bottom section and select Make New Request
keng mak

2023-06-02 07:19 UTC, colmazia commented on docs/develop/02-developer-guides/how-to-use-bandchain-in-evm-contract.md
> +![](https://hackmd.io/_uploads/BJCsRqHLn.png)
ok

2023-06-02 07:19 UTC, colmazia commented on docs/develop/02-developer-guides/how-to-use-bandchain-in-evm-contract.md
> +If you are not sure what is the appropriate number, you can input 0.
I think 0 is okay?

2023-06-02 07:40 UTC, colmazia commented on docs/develop/02-developer-guides/how-to-use-bandchain-in-evm-contract.md
> +If you are not sure what is the appropriate number, you can input 0.
but P folk said 3 so I will put 3

2023-06-02 07:47 UTC, colmazia commented on docs/develop/02-developer-guides/how-to-use-bandchain-in-evm-contract.md
> +In essence, a Bridge Contract is a smart contract facilitated by Band Protocol, designed to validate the authenticity of data received by your contract across various blockchains. A list of supported
ok

2023-06-02 07:48 UTC, colmazia commented on docs/develop/02-developer-guides/how-to-use-bandchain-in-evm-contract.md
> +Band Protocol also provides additional libraries, such as Pyband and Bandchain.js, that aid in building data-relaying programs. You can explore more about these resources on their respective pages he
ok

2023-06-02 10:25 UTC, RogerKSI commented on docs/develop/02-developer-guides/how-to-use-bandchain-in-evm-contract.md
> +<img src="https://hackmd.io/_uploads/S1SQOeCrn.png" height="300">
seems it doesn't allow to use html tag. @colmazia

2023-06-02 10:26 UTC, RogerKSI commented on docs/develop/02-developer-guides/how-to-use-bandchain-in-evm-contract.md
> +<img src="https://hackmd.io/_uploads/S1SQOeCrn.png" height="300">
two choices from p'pang
- use .mdx file
- use normal syntax.

2023-06-06 09:14 UTC, xxibcill requested changes

2023-06-06 09:14 UTC, xxibcill commented on docs/develop/02-developer-guides/how-to-use-bandchain-in-evm-contract.md
> +<img src="https://hackmd.io/_uploads/S1SQOeCrn.png" height="300">
don't use src url from https://hackmd.io, There is a possibility that it may be removed.

put image file in `static/img`
and use like this
```suggestion
![explain about image](/img/your-image-name.png)
```

2023-06-06 15:00 UTC, taobun commented on docs/develop/02-developer-guides/how-to-use-bandchain-in-evm-contract.md
> +If you are not sure what is the appropriate number, you can input 3 as the standard.
Should we split 1 and 2 to input of script and other is bandchain request config?

2023-06-06 15:00 UTC, taobun commented on docs/develop/02-developer-guides/how-to-use-bandchain-in-evm-contract.md
> +To integrate BandChain data into your contract, you need to accomplish two things. Firstly, your contract must implement the BandBridgeConsumer contract. Secondly, you must establish the function han
must inherit? by implement `_handleOracleResponse` callback function when you got the verified data from bridge

2023-06-07 06:11 UTC, colmazia commented on docs/develop/02-developer-guides/how-to-use-bandchain-in-evm-contract.md
> +<img src="https://hackmd.io/_uploads/S1SQOeCrn.png" height="300">
how can I resize the image if I use it like that, or should I resize it before?

2023-06-08 06:24 UTC, babybunn approved these changes

2023-06-08 06:30 UTC, babybunn commented
## ⚠️ Warning

**This pull request can only be merged when the Falcon documentation and repository are ready to public.**

2023-12-04 07:08 UTC, RogerKSI commented
This PR needs to merge after Falcon is launched.

2025-08-13 07:56 UTC, closed without merging